# backend/modifier.py
from docx import Document
from io import BytesIO
import datetime

def build_modified_docx_bytes(original_filename: str, clauses: dict) -> bytes:
    """
    Create a simple DOCX containing an Addendum with provided clauses.
    Returns raw bytes for download.
    """
    doc = Document()
    doc.add_heading("Contract Modification — Addendum", level=1)
    doc.add_paragraph(f"Original file: {original_filename}")
    doc.add_paragraph(f"Generated: {datetime.datetime.utcnow().isoformat()} UTC")
    doc.add_paragraph("This addendum was generated by AI Compliance Checker to address missing clauses.")
    doc.add_heading("Addendum", level=2)
    if not clauses:
        doc.add_paragraph("No clauses provided.")
    else:
        for name, text in clauses.items():
            doc.add_heading(name, level=3)
            doc.add_paragraph(text)
    bio = BytesIO()
    doc.save(bio)
    return bio.getvalue()
